// src/components/DropZone.tsx
import React, { useCallback, useState, useEffect } from 'react';
import { Upload, FolderOpen } from 'lucide-react';
import { open } from '@tauri-apps/api/dialog';
import { invoke } from '@tauri-apps/api/tauri';
import { listen } from '@tauri-apps/api/event';
import { MEDIA_EXTENSIONS } from '@/constants';
import { getDefaultFormat, getDefaultSettings, generateFileId } from '@/utils';
import type { FileItem, MediaInfo } from '@/types';

interface DropZoneProps {
  onFilesAdded: (files: FileItem[]) => void;
}

const DropZone: React.FC<DropZoneProps> = React.memo(({ onFilesAdded }) => {
  const [isDragging, setIsDragging] = useState(false);

  const processFiles = useCallback(
    async (paths: string[]) => {
      const results = await Promise.allSettled(
        paths.map(async path => {
          const mediaInfo = await invoke<MediaInfo>('detect_media_type', { path });
          const fileName = path.split(/[\\/]/).pop() || path;
          return {
            id: generateFileId(),
            path,
            name: fileName,
            mediaInfo,
            outputFormat: getDefaultFormat(mediaInfo.media_type),
            settings: getDefaultSettings(mediaInfo.media_type, false),
            status: 'pending' as const,
            progress: null,
            error: null,
            addedAt: Date.now(),
          };
        })
      );

      const fileItems: FileItem[] = [];
      const errors: string[] = [];

      results.forEach(result => {
        if (result.status === 'fulfilled') {
          fileItems.push(result.value);
        } else {
          errors.push(result.reason);
        }
      });

      if (fileItems.length > 0) onFilesAdded(fileItems);

      if (errors.length > 0) {
        alert(`Failed to process ${errors.length} file(s): ${errors[0]}`);
      }
    },
    [onFilesAdded]
  );

  const handleBrowse = useCallback(
    async (e?: React.MouseEvent) => {
      e?.stopPropagation();
      try {
        const selected = await open({
          multiple: true,
          filters: [{ name: 'Media Files', extensions: [...MEDIA_EXTENSIONS] }],
        });
        if (selected) {
          await processFiles(Array.isArray(selected) ? selected : [selected as string]);
        }
      } catch (error) {
        console.error('File selection error:', error);
      }
    },
    [processFiles]
  );

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback(
    async (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setIsDragging(false);

      const files = Array.from(e.dataTransfer.files) as (File & { path: string })[];
      const paths = files.map(f => f.path).filter(Boolean);
      if (paths.length > 0) await processFiles(paths);
    },
    [processFiles]
  );

  useEffect(() => {
    const unlisten = listen<string[]>('tauri://file-drop', async event => {
      await processFiles(event.payload);
    });
    return () => {
      unlisten.then(fn => fn());
    };
  }, [processFiles]);

  return (
    <div
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
      onClick={handleBrowse}
      className={`glass px-6 py-4 flex items-center justify-between gap-4 h-full cursor-pointer transition-all duration-200 border-2 border-dashed rounded-xl
        ${isDragging ? 'border-primary-purple bg-primary-purple/10 scale-[1.01]' : 'border-white/20 hover:border-primary-pink/50'}`}
    >
      <div className="flex items-center gap-4">
        <Upload
          size={32}
          className={`transition-all ${isDragging ? 'text-primary-purple scale-110' : 'text-white/40'}`}
        />
        <div>
          <p className="text-white text-lg font-bold">Drop media files here</p>
          <p className="text-white/60 text-sm">Audio & Video • 40+ formats supported</p>
        </div>
      </div>

      <button
        onClick={handleBrowse}
        className="flex items-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/20 rounded-lg transition-all font-semibold text-white flex-shrink-0"
      >
        <FolderOpen size={20} />
        <span>Browse Files</span>
      </button>
    </div>
  );
});

DropZone.displayName = 'DropZone';

export default DropZone;

// src/components/DropZone.svelte
<script lang="ts">
  import { Upload } from 'lucide-svelte';
  import { open } from '@tauri-apps/plugin-dialog';
  import { listen } from '@tauri-apps/api/event';
  import { MEDIA_EXTENSIONS } from '@/constants';
  import { processFilePaths } from '@/utils/fileHelpers';
  import type { FileItem } from '@/types';

  interface DragDropPayload {
    paths: string[];
    position: { x: number; y: number };
  }

  interface Props {
    onFilesAdded: (files: FileItem[]) => void;
    currentCount: number;
    maxCount: number;
    compact?: boolean;
  }

  let { onFilesAdded, currentCount, maxCount, compact = false }: Props = $props();

  let isDragging = $state(false);
  let isProcessing = $state(false);

  let isFull = $derived(currentCount >= maxCount);
  let isDisabled = $derived(isFull || isProcessing);

  async function handlePaths(paths: string[]) {
    if (paths.length === 0) return;
    isProcessing = true;
    try {
      const files = await processFilePaths(paths);
      if (files.length > 0) onFilesAdded(files);
    } finally {
      isProcessing = false;
    }
  }

  async function handleBrowse() {
    if (isDisabled) return;
    try {
      const selected = await open({
        multiple: true,
        filters: [{ name: 'Media Files', extensions: [...MEDIA_EXTENSIONS] }],
      });
      if (selected) {
        const paths = Array.isArray(selected) ? selected : [selected];
        await handlePaths(paths);
      }
    } catch (error) {
      console.error('File selection error:', error);
    }
  }

  $effect(() => {
    const promises = [
      listen<DragDropPayload>('tauri://drag-drop', async (event) => {
        isDragging = false;
        await handlePaths(event.payload.paths);
      }),
      listen<DragDropPayload>('tauri://drag-over', () => {
        isDragging = true;
      }),
      listen('tauri://drag-leave', () => {
        isDragging = false;
      }),
    ];

    const unlisteners = Promise.all(promises);

    return () => {
      unlisteners.then((fns) => fns.forEach((fn) => fn()));
    };
  });
</script>

{#if compact}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    onclick={isDisabled ? undefined : handleBrowse}
    class="w-full py-2 flex items-center justify-center gap-2 border border-dashed rounded transition-all cursor-pointer
      {isFull
        ? 'border-red-500/30 opacity-50 cursor-not-allowed'
        : isDragging
          ? 'border-blue-500 bg-blue-500/10'
          : 'border-white/10 hover:border-blue-500/30 hover:bg-white/5'}"
  >
    <Upload size={14} class="text-white/40" />
    <span class="text-xs text-white/40 font-medium">Add more files...</span>
  </div>
{:else}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    onclick={isDisabled ? undefined : handleBrowse}
    class="w-full py-12 flex flex-col items-center justify-center gap-4 border border-dashed rounded-xl transition-all cursor-pointer bg-[#0f172a]/50
      {isFull
        ? 'border-red-500/30 cursor-not-allowed opacity-50'
        : isDragging
          ? 'border-blue-500 bg-blue-500/5 scale-[1.01]'
          : isProcessing
            ? 'border-blue-500/50'
            : 'border-white/10 hover:border-blue-500/50 hover:bg-white/5'}"
  >
    <div
      class="p-4 rounded-full transition-colors {isDragging
        ? 'bg-blue-500/20 text-blue-400'
        : 'bg-white/5 text-white/30'}"
    >
      {#if isProcessing}
        <div class="w-8 h-8 border-2 border-current border-t-transparent rounded-full animate-spin"></div>
      {:else}
        <Upload size={32} />
      {/if}
    </div>
    <div class="text-center">
      <p class="text-lg font-medium text-white/80">
        {#if isFull}
          Queue Full
        {:else if isProcessing}
          Analyzing...
        {:else}
          Drop files here
        {/if}
      </p>
      <p class="text-sm text-white/40 mt-1">or click to browse</p>
    </div>
  </div>
{/if}
