// src/components/GpuIndicator.svelte
<script lang="ts">
  import { Cpu, Zap } from 'lucide-svelte';
  import type { GpuInfo } from '@/types';

  interface Props {
    gpuInfo: GpuInfo;
    compact?: boolean;
  }

  let { gpuInfo, compact = false }: Props = $props();
</script>

{#if compact}
  <div class="flex items-center gap-1.5 text-xs">
    {#if gpuInfo.available}
      <Zap size={12} class="text-yellow-400" />
      <span class="text-white/60">{gpuInfo.name}</span>
    {:else}
      <Cpu size={12} class="text-orange-400" />
      <span class="text-white/40">CPU Only</span>
    {/if}
  </div>
{:else}
  <div class="glass px-3 py-2 flex items-center gap-2">
    {#if gpuInfo.available}
      <Zap size={16} class="text-yellow-400" />
      <div>
        <div class="text-white text-sm font-medium">{gpuInfo.name}</div>
        <div class="text-white/40 text-xs">GPU Acceleration</div>
      </div>
    {:else}
      <Cpu size={16} class="text-orange-400" />
      <div>
        <div class="text-white text-sm font-medium">CPU Only</div>
        <div class="text-white/40 text-xs">No GPU Detected</div>
      </div>
    {/if}
  </div>
{/if}

// src/components/GpuIndicator.tsx
import React from 'react';
import { motion } from 'framer-motion';
import { Cpu, Zap } from 'lucide-react';
import type { GpuInfo } from '@/types';

interface GpuIndicatorProps {
  gpuInfo: GpuInfo;
}

const GPU_COLORS: Record<GpuInfo['vendor'], string> = {
  nvidia: 'bg-green-500',
  intel: 'bg-blue-500',
  amd: 'bg-red-500',
  apple: 'bg-gray-500',
  none: 'bg-orange-500',
};

const GpuIndicator: React.FC<GpuIndicatorProps> = React.memo(({ gpuInfo }) => (
  <motion.div
    initial={{ opacity: 0, scale: 0.9 }}
    animate={{ opacity: 1, scale: 1 }}
    className="glass px-4 py-2 flex items-center gap-3"
  >
    <div className={`w-3 h-3 rounded-full ${GPU_COLORS[gpuInfo.vendor]} animate-pulse`} />
    {gpuInfo.available ? (
      <>
        <Zap size={18} className="text-yellow-400" />
        <div className="flex flex-col">
          <span className="text-white text-sm font-semibold">{gpuInfo.name}</span>
          <span className="text-white/50 text-xs">GPU Acceleration Available</span>
        </div>
      </>
    ) : (
      <>
        <Cpu size={18} className="text-orange-400" />
        <div className="flex flex-col">
          <span className="text-white text-sm font-semibold">CPU Only</span>
          <span className="text-white/50 text-xs">No GPU Detected</span>
        </div>
      </>
    )}
  </motion.div>
));

GpuIndicator.displayName = 'GpuIndicator';

export default GpuIndicator;
